### ISSUE TITLE
Resource pool being null 

### ISSUE THREAD

**Issue by desalegnyi** [jscarle/HyperV.NET#15]
am trying to create a virtual machine but resourcePool  is being null for resourceSubType = "Microsoft:Hyper-V:Memory" and resourcePoolClass = "Msvm_ResourcePool":-

   ObjectQuery query = new ObjectQuery($"SELECT * FROM {resourcePoolClass} WHERE ResourceSubType = \"{resourceSubType}\" AND Primordial = True");
            using (ManagementObjectSearcher searcher = new ManagementObjectSearcher(virtualizationScope, query))
            using (ManagementObject resourcePool = searcher.Get().First())

Please how may I resolve this issue?

**Comment by jscarle** [comment]
I no longer have access to an environment in which I can test this.
