### ISSUE TITLE
Dear author Hello, may I ask how the following functions are implemented? I do not understand the code you wrote, so I would like to submit this inquiry

### ISSUE THREAD

**Issue by tuke-code** [jscarle/HyperV.NET#21]
Hello, may I ask how to call the vhdx template when creating a VM, and then use the password configured by myself as the login password? For example, I place the vhdx template of Centos7.9 in a directory, obtain the template name during installation, install the system, and use the system password defined by myself after installation

**Comment by jscarle** [comment]
You question is outside of the scope of this project.
